server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    consul:
      discovery:
        service-name: ${spring.application.name}
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_routh
          uri: lb://cloud-provider-payment
          predicates:
            - Path=/payment/get/**
        - id: payment_routh2
          uri: lb://cloud-provider-payment
          predicates:
            - Path=/payment/lb/**
            - After=2020-02-21T15:00:00:00.000+08:00[Asia/Shanghai] # 该路由在此时间后生效 很多定时开启的任务，可以用
            - Before
            - Between
            - Cookie
            - Header
            - Host
            - Method
            - Path
            - Query
          filters:
            - Filter=xxx
